### PR TITLE
Add new gauge to show the count of mon in down state.

### PR DESCRIPTION
**Pull request by shminjs**
When a monitor is down, it should be urgent to notice administrator.

Signed-off-by: shminjs <shminjs@outlook.com>

### CODE REVIEW

**Review by baergj — APPROVED** [review]

**Comment by baergj** [comment]
Thanks!

**Comment by neurodrone** [comment]
We already have a [`monitor_quorum_count`](https://github.com/digitalocean/ceph_exporter/blob/nautilus/collectors/monitors.go#L181-L187) metric which this is slightly redundant to, since we get down MONs today by subtracting that from active MON count. Also this change probably should be in `monitors.go`.

**Comment by baergj** [comment]
`monitor_quorum_count` isn't great to alert on since the expected monitor count is not exported today.

Re: Placement - since this is interpreting the health status output, it seems to be the right place, though I would agree that it's a bit of a grey area.

**Comment by neurodrone** [comment]
Good point! I assumed the total mon node count we see internally was coming from `ceph_exporter` but looks like we were gathering it from somewhere else. I'd still think this should be placed in `monitor.go` since it does pull monitor specific metrics from health status but that's a relatively trivial change to make.

**Comment by MattIPv4** [comment]
Hey, @shminjs - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Pull request merged**
