### PR TITLE
health/pgs: track misplaced objects from their pgs

### PR DESCRIPTION
**Pull request by neurodrone**
cc: @cagedmantis @mdlayher

### CODE REVIEW

**Comment by mdlayher** [comment]
+1, though I think it may be time to begin refactoring some of these very regex parsing routines out so we can reduce code verbosity.  That can happen in another PR.

**Comment by neurodrone** [comment]
Curious to know what you are thinking. :)

**Comment by mdlayher** [comment]
Let me get back to you on that one.  In the mean time, :+1: .

**Comment by neurodrone** [comment]
Cool :+1: , merging this in for now.

**Pull request merged**
